on:
  push:
    branches: [master]
name: Flatpak Build
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: io.github.qwersyk.Wienere.flatpak
          manifest-path: io.github.qwersyk.Wienere.json
          cache-key: flatpak-builder-${{ github.sha }}
